Repository meotitda/DICTIONARY, pull requests merged in 2020-11, with the labels that each got.

#5 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: DOCUMENTATION 📕, NEW ⚡️

#8 [FIX] check on keyword fix to push
  .github/workflows/check.yml
  README.md
Labels: API 💻, BUG 👿

#9 [ADD&FIX] beginnerDoc & others
  2TAT1C/markdown_preview.png
  2TAT1C/process_1-1.png
  2TAT1C/process_1-2.png
  2TAT1C/process_2.png
  2TAT1C/process_7.png
  2TAT1C/process_8-1.png
  2TAT1C/process_8-2.png
  2TAT1C/process_8-3.png
  2TAT1C/process_9.png
  docs/CONTRIBUTE.md
  docs/SyntaxDoc.md
  docs/ToGitBeginner.md
  package.json
Labels: DOCUMENTATION 📕, EDIT 🛠, NEW ⚡️

#11 [Feature/ADD] python inspect
  inspect.py
Labels: API 💻, CHECKED ✔️, NEW ⚡️

#12 [Fix] hashtag function
  __pycache__/inspect.cpython-37.pyc
  inspect.py
Labels: API 💻, CHECKED ✔️, EDIT 🛠

#14 fix syntax error
  .github/workflows/check.yml
Labels: API 💻, BUG 👿

#15 [Fix] Build fails due to dependency issues during deployment
  .github/workflows/check.yml
  inspect.js
  inspect.py
Labels: API 💻, BUG 👿, EDIT 🛠

#7 [WORD/ADD] Headless 단어 추가
  DIC/H/Headless.md
  README.md
Labels: CHECKED ✔️, NEW ⚡️, WORD 📝

#20 임시적으로 AST link 수정
  README.md
Labels: DOCUMENTATION 📕, EDIT 🛠

#25 [WORD/ADD] OOP
  DIC/O/OOP.md
Labels: CHECKED ✔️, NEW ⚡️, WORD 📝

#26 OOP MERGE
  README.md
Labels: NEW ⚡️, WORD 📝

#27 #24 Load 문제에 정답 기재되었음 -> 수정
  DIC/L/Load.md
Labels: EDIT 🛠, WORD 📝

#28 Update SyntaxDoc.md
  docs/SyntaxDoc.md
Labels: DOCUMENTATION 📕, EDIT 🛠

#29 Update CONTRIBUTE.md For DICTIONARY-EDITOR Beta
  README.md
  docs/CONTRIBUTE.md
Labels: DOCUMENTATION 📕, EDIT 🛠

#33 Add Fuzzy matching
  DIC/F/Fuzzy matching.md
  README.md
Labels: NEW ⚡️, WORD 📝

#37 🐛 fix label format & 🔥 add ignore dictionary-client
  .gitignore
  DIC/A/AST.md
Labels: BUG 👿, EDIT 🛠
